export type SDRManualItem = {
  id: string;
  question: string;
  shortAnswer: string;
  answer: string;
  tags: string[];
  priority?: 'qualified' | 'review' | 'disqualified';
};

export type SDRManualCategory = {
  category: string;
  description: string;
  items: SDRManualItem[];
};

export const sdrChecklist = [
  'Nome completo do contratante',
  'CPF/CNPJ do contratante',
  'Telefone',
  'Cidade/UF',
  'Tipo de imóvel',
  'Distribuidora',
  'Valor médio da conta',
  'Consumo médio, quando disponível',
  'Número da Unidade Consumidora (UC)',
  'A titularidade da UC está em nome do contratante?',
  'Todas as UCs envolvidas no rateio estão em nome do contratante?',
  'O imóvel é próprio?',
  'Possui autorização do proprietário, se aplicável?',
  'Possui energia solar instalada?',
  'Interesse: Leasing, Venda, Monitoramento, Assistência ou Dúvida',
  'Conta de energia recebida?',
  'Lead qualificado?',
  'Encaminhado ao consultor?',
];

export const quickQualificationCriteria = [
  'Goiás: conta média igual ou superior a R$ 500,00/mês',
  'Distrito Federal: conta média igual ou superior a R$ 600,00/mês',
  'Prioridade alta: acima de R$ 1.000,00/mês',
  'Prioridade máxima: acima de R$ 2.000,00/mês',
  'Priorizar clientes comerciais, rurais e residenciais de alto consumo',
  'Desqualificar leads que querem vender energia, vender terreno, alugar terreno, oferecer parceria de usina ou apresentar projeto de terceiro',
];

export const sdrManual: SDRManualCategory[] = [
  { category: 'Visão geral da SolarInvest', description: 'Posicionamento, papel do SDR e limites comerciais.', items: [
    { id: 'o-que-e-a-solarinvest', question: 'O que é a SolarInvest?', shortAnswer: 'Empresa especializada em energia solar, com foco em Leasing Solar e soluções fotovoltaicas.', answer: 'A SolarInvest é uma empresa especializada em soluções de energia solar. Nosso principal modelo de negócio é o Leasing Solar, no qual a própria SolarInvest realiza o investimento no sistema fotovoltaico e o cliente passa a pagar uma mensalidade normalmente inferior ao que pagava anteriormente pela energia elétrica. Também atuamos com venda de sistemas fotovoltaicos, monitoramento, assistência técnica, ampliação e adequação de usinas já existentes.', tags: ['solarinvest', 'empresa', 'leasing solar', 'energia solar'], priority: 'qualified' },
  ]},
  { category: 'Leasing Solar', description: 'Conceitos, propriedade, manutenção e regras gerais do leasing.', items: [
    { id: 'o-que-e-leasing-solar', question: 'O que é Leasing Solar?', shortAnswer: 'A SolarInvest investe no sistema e o cliente paga uma mensalidade pelo uso da usina.', answer: 'No Leasing Solar, a SolarInvest realiza o investimento necessário para aquisição e instalação do sistema fotovoltaico. O cliente não precisa comprar os equipamentos e passa a utilizar a energia gerada pela usina mediante pagamento de uma mensalidade prevista em contrato. Durante a vigência contratual, a SolarInvest permanece responsável pela operação, monitoramento e manutenção previstos no contrato. Ao término do prazo contratual, a propriedade do sistema pode ser transferida ao cliente conforme as condições contratuais.', tags: ['leasing', 'aluguel solar', 'sem entrada', 'mensalidade', 'sistema solar'], priority: 'qualified' },
    { id: 'cliente-precisa-dar-entrada', question: 'O cliente precisa dar entrada?', shortAnswer: 'Na maioria dos projetos de leasing, não há investimento inicial, mas todo caso passa por análise.', answer: 'Na maioria dos projetos de Leasing Solar, não há necessidade de investimento inicial por parte do cliente. No entanto, cada caso passa por análise técnica, financeira e documental para confirmar viabilidade. O SDR deve evitar afirmar aprovação automática.', tags: ['entrada', 'investimento inicial', 'sem entrada', 'aprovação'], priority: 'review' },
    { id: 'leasing-exige-investimento-inicial', question: 'O Leasing Solar exige investimento inicial?', shortAnswer: 'Normalmente não, mas a viabilidade depende da análise técnica, financeira e documental.', answer: 'Em regra, o Leasing Solar é apresentado como alternativa para reduzir a conta sem compra imediata do sistema. Ainda assim, a SolarInvest precisa validar consumo, imóvel, documentação e condições do projeto antes de confirmar qualquer condição comercial.', tags: ['entrada', 'investimento inicial', 'leasing', 'sem entrada'], priority: 'review' },
    { id: 'sistema-e-do-cliente', question: 'O sistema é do cliente?', shortAnswer: 'Durante o leasing, o sistema é da SolarInvest; ao final, pode ser transferido conforme contrato.', answer: 'Durante a vigência do Leasing Solar, o sistema permanece de propriedade da SolarInvest. O cliente recebe o direito de uso da usina e os benefícios econômicos previstos no contrato. Ao final do prazo contratual, a propriedade poderá ser transferida ao cliente conforme as condições contratuais.', tags: ['propriedade', 'cliente', 'contrato', 'transferência'], priority: 'review' },
    { id: 'quem-faz-a-manutencao', question: 'Quem faz a manutenção?', shortAnswer: 'A SolarInvest executa os serviços previstos em contrato durante o leasing.', answer: 'Durante o período do Leasing Solar, a SolarInvest é responsável pelos serviços previstos em contrato, incluindo monitoramento remoto e manutenção corretiva do sistema, conforme regras contratuais.', tags: ['manutenção', 'monitoramento', 'leasing'], priority: 'qualified' },
    { id: 'quem-paga-se-quebrar-equipamento', question: 'Quem paga se quebrar um equipamento?', shortAnswer: 'Depende da origem da falha, garantias aplicáveis e condições contratuais.', answer: 'Quando o defeito estiver coberto pelas garantias contratuais ou do fabricante, a SolarInvest acompanha e executa os procedimentos previstos. Cada situação precisa ser analisada conforme a origem da falha, as garantias aplicáveis e as condições do contrato.', tags: ['equipamento', 'quebrar', 'garantia', 'defeito'], priority: 'review' },
    { id: 'cliente-pode-vender-imovel', question: 'O cliente pode vender o imóvel?', shortAnswer: 'Sim, mas deve comunicar a SolarInvest para avaliar alternativas contratuais.', answer: 'Sim. Em caso de venda do imóvel, a SolarInvest deverá ser comunicada para avaliar as alternativas possíveis, como transferência contratual para o novo proprietário, quitação antecipada ou outra solução aplicável ao caso concreto.', tags: ['vender imóvel', 'transferência contratual', 'quitação'], priority: 'review' },
  ]},
  { category: 'Qualificação de leads', description: 'Critérios mínimos, prioridades e perguntas de triagem.', items: [
    { id: 'qualifica-leasing-goias', question: 'Qual cliente qualifica para Leasing Solar em Goiás?', shortAnswer: 'Prioridade inicial: conta média igual ou superior a R$ 500,00/mês.', answer: 'Para Goiás, a prioridade inicial são clientes com conta média de energia igual ou superior a R$ 500,00 por mês. Contas abaixo desse valor normalmente não qualificam para Leasing Solar, salvo análise estratégica específica.', tags: ['goiás', 'goias', '500', 'qualificação', 'conta'], priority: 'qualified' },
    { id: 'qualifica-leasing-distrito-federal', question: 'Qual cliente qualifica para Leasing Solar no Distrito Federal?', shortAnswer: 'Prioridade inicial: conta média igual ou superior a R$ 600,00/mês.', answer: 'Para o Distrito Federal, a prioridade inicial são clientes com conta média de energia igual ou superior a R$ 600,00 por mês. Contas abaixo desse valor normalmente não qualificam para Leasing Solar, salvo análise estratégica específica.', tags: ['df', 'distrito federal', 'brasília', '600', 'qualificação'], priority: 'qualified' },
    { id: 'qual-perfil-tem-prioridade', question: 'Qual perfil tem prioridade?', shortAnswer: 'Comercial, rural e residencial de alto consumo, especialmente acima de R$ 1.000,00/mês.', answer: 'A SolarInvest prioriza clientes comerciais, rurais e residenciais de maior consumo. Quanto maior a conta de energia, maior tende a ser a viabilidade econômica do projeto. Clientes acima de R$ 1.000,00 por mês devem ser tratados como prioridade comercial. Clientes acima de R$ 2.000,00 por mês devem ser tratados como prioridade máxima.', tags: ['prioridade', 'alto consumo', 'comercial', 'rural', 'residencial'], priority: 'qualified' },
    { id: 'perguntas-para-qualificar', question: 'Quais perguntas o SDR deve fazer para qualificar?', shortAnswer: 'Coletar cidade/UF, conta média, imóvel, titularidade, distribuidora, solar existente, interesse e conta de energia.', answer: 'O SDR deve perguntar: cidade e estado do cliente; valor médio da conta de energia; tipo de imóvel; se o imóvel é próprio; se a conta está no nome do cliente; qual a distribuidora; se já possui energia solar; se deseja reduzir a conta sem investir ou comprar o sistema; e se pode enviar a última conta de energia para análise.', tags: ['perguntas', 'qualificar', 'triagem', 'checklist'], priority: 'qualified' },
  ]},
  { category: 'Perguntas financeiras', description: 'Mensalidade, restrição financeira e análise comercial.', items: [
    { id: 'entender-perfil-financeiro', question: 'Como entender o perfil financeiro do cliente?', shortAnswer: 'Entender conta mensal, recorrência, interesse, imóvel próprio e abertura para análise documental.', answer: 'O SDR deve identificar quanto o cliente paga de energia por mês, se esse valor é recorrente, se o cliente tem interesse em reduzir custo mensal, se busca leasing sem entrada ou compra direta, se o imóvel é próprio e se há disponibilidade para análise documental. O SDR não deve solicitar dados sensíveis de crédito nesta fase, mas pode identificar se o cliente tem condições mínimas e interesse real.', tags: ['financeiro', 'perfil', 'crédito', 'documental'], priority: 'review' },
    { id: 'cliente-nome-restrito', question: 'O cliente com nome restrito pode contratar?', shortAnswer: 'Depende de análise financeira, documental e de risco.', answer: 'A contratação depende de análise financeira, documental e de risco. O SDR não deve reprovar automaticamente, mas deve informar que a proposta passa por análise interna e poderá exigir corresponsável financeiro, garantias adicionais ou não ser aprovada.', tags: ['nome restrito', 'spc', 'serasa', 'crédito', 'análise'], priority: 'review' },
    { id: 'mensalidade-fixa', question: 'A mensalidade é fixa?', shortAnswer: 'Não necessariamente; pode acompanhar variações tarifárias e regras contratuais.', answer: 'Não necessariamente. A mensalidade pode acompanhar variações tarifárias da distribuidora, da ANEEL e das regras previstas no contrato. O SDR deve explicar que o consultor apresentará a simulação com base na proposta comercial.', tags: ['mensalidade', 'fixa', 'reajuste', 'aneel', 'tarifa'], priority: 'review' },
  ]},
  { category: 'Documentação necessária', description: 'Documentos iniciais e importância da conta de energia.', items: [
    { id: 'documentos-atendimento-inicial', question: 'Quais documentos solicitar no atendimento inicial?', shortAnswer: 'Principalmente a última conta de energia e dados básicos do cliente.', answer: 'No atendimento inicial, o SDR deve solicitar principalmente a última conta de energia. Também deve coletar nome completo, telefone, cidade, estado, tipo de imóvel e informar se o cliente é proprietário ou possui autorização do proprietário. Documentos adicionais serão solicitados pelo consultor ou pela equipe operacional, conforme avanço da negociação.', tags: ['documentos', 'conta de energia', 'atendimento inicial'], priority: 'qualified' },
    { id: 'por-que-precisamos-da-conta', question: 'Por que precisamos da conta de energia?', shortAnswer: 'Para verificar consumo, valor médio, UC, titularidade, distribuidora e viabilidade.', answer: 'A conta de energia permite verificar consumo, valor médio, unidade consumidora, titularidade, distribuidora, tipo de ligação e dados necessários para avaliar viabilidade técnica e comercial. Sem a conta, a proposta será apenas estimativa.', tags: ['conta de energia', 'fatura', 'viabilidade', 'distribuidora'], priority: 'qualified' },
  ]},
  { category: 'Instalação e homologação', description: 'Prazos, aprovação da distribuidora e vistoria.', items: [
    { id: 'tempo-instalacao', question: 'Quanto tempo demora a instalação?', shortAnswer: 'Depende de documentação, distribuidora, equipamentos, vistoria, adequações e cronograma.', answer: 'O prazo depende da análise documental, aprovação junto à distribuidora, disponibilidade dos equipamentos, vistoria técnica, necessidade de adequações elétricas e cronograma de instalação. O SDR não deve prometer prazo definitivo antes da avaliação técnica.', tags: ['instalação', 'prazo', 'homologação'], priority: 'review' },
    { id: 'quem-aprova-projeto', question: 'Quem aprova o projeto?', shortAnswer: 'A distribuidora aprova conforme procedimentos técnicos e regulatórios.', answer: 'O projeto precisa passar pelos procedimentos técnicos e regulatórios da distribuidora de energia. A SolarInvest prepara e acompanha o processo, mas prazos, vistorias e aprovações dependem também da distribuidora e da regularidade da unidade consumidora.', tags: ['aprovação', 'projeto', 'distribuidora', 'homologação'], priority: 'review' },
    { id: 'cliente-presente-vistoria', question: 'O cliente precisa estar presente na vistoria?', shortAnswer: 'Sim, o cliente ou representante deve permitir acesso quando necessário.', answer: 'Sim, o cliente ou um representante deve estar disponível quando necessário para permitir acesso ao imóvel e acompanhar vistoria da concessionária. A ausência pode atrasar ou impedir a aprovação do sistema.', tags: ['vistoria', 'cliente presente', 'concessionária'], priority: 'review' },
  ]},
  { category: 'Conta de energia e distribuidora', description: 'Faturas, créditos e responsabilidades da distribuidora.', items: [
    { id: 'cliente-recebe-conta-distribuidora', question: 'O cliente continuará recebendo conta da distribuidora?', shortAnswer: 'Sim, poderá receber cobranças de disponibilidade, iluminação, tributos e consumo não compensado.', answer: 'Sim. Mesmo com energia solar, o cliente pode continuar recebendo faturas da distribuidora com cobranças como custo de disponibilidade, iluminação pública, tributos, encargos e eventual consumo não compensado, conforme o caso.', tags: ['conta', 'distribuidora', 'fatura', 'custo de disponibilidade'], priority: 'review' },
    { id: 'titularidade-uc-contratante', question: 'A titularidade da UC precisa estar no nome do contratante?', shortAnswer: 'Sim. Para Leasing Solar, a Unidade Consumidora deve estar em nome do contratante.', answer: 'Sim. Para contratação do Leasing Solar, a titularidade da Unidade Consumidora (UC) deve estar em nome do contratante. Caso a conta de energia esteja em nome de outra pessoa física ou jurídica, a regularização da titularidade deverá ser realizada antes da formalização do contrato ou conforme orientação específica da SolarInvest. Essa verificação deve fazer parte do checklist obrigatório do SDR.', tags: ['titularidade', 'UC', 'unidade consumidora', 'contratante', 'conta de energia', 'leasing', 'checklist'], priority: 'qualified' },
    { id: 'todas-ucs-nome-contratante', question: 'Todas as Unidades Consumidoras precisam estar no nome do contratante?', shortAnswer: 'Sim. As UCs utilizadas no contrato e no rateio devem estar em nome do contratante.', answer: 'Sim. Para utilização de créditos, rateio ou compensação vinculada ao contrato, as Unidades Consumidoras devem estar em nome do contratante ou atender às regras legais e regulatórias aplicáveis da distribuidora. Em regra, a SolarInvest deve orientar o cliente de que todas as UCs envolvidas precisam estar regularizadas em nome do contratante para evitar atrasos, recusas ou problemas de compensação.', tags: ['UC', 'unidades consumidoras', 'titularidade', 'rateio', 'créditos', 'compensação', 'contratante', 'distribuidora'], priority: 'qualified' },
    { id: 'responsavel-alterar-rateio-creditos', question: 'Quem é responsável por solicitar ou alterar o rateio dos créditos?', shortAnswer: 'O contratante é responsável pelas solicitações e alterações de rateio.', answer: 'A solicitação de inclusão, exclusão ou alteração de rateio de créditos junto à distribuidora é de responsabilidade do contratante. A SolarInvest pode auxiliar com orientações, documentos e acompanhamento quando possível, mas não deve prometer controle sobre o prazo, aceitação ou processamento da solicitação pela distribuidora.', tags: ['rateio', 'alteração de rateio', 'créditos', 'compensação', 'distribuidora', 'contratante', 'responsabilidade'], priority: 'review' },
    { id: 'garantia-compensacao-apos-rateio', question: 'A SolarInvest garante a compensação dos créditos após alteração de rateio?', shortAnswer: 'Não. A compensação depende do processamento da distribuidora.', answer: 'Não. A compensação dos créditos depende exclusivamente do processamento realizado pela distribuidora de energia. Alterações de rateio podem gerar atrasos na compensação e a SolarInvest não consegue garantir datas, valores ou ciclos exatos de compensação. O SDR deve explicar que a SolarInvest pode auxiliar o cliente, mas não controla os prazos internos da distribuidora.', tags: ['rateio', 'compensação', 'créditos', 'distribuidora', 'atraso', 'fatura', 'SolarInvest'], priority: 'review' },
    { id: 'alteracoes-rateio-atrasam-compensacao', question: 'Alterações no rateio podem atrasar a compensação dos créditos?', shortAnswer: 'Sim. Alterações de rateio tendem a gerar atraso temporário na compensação.', answer: 'Sim. Solicitações ou alterações de rateio podem gerar atraso temporário na compensação dos créditos de energia, pois dependem da análise e processamento da distribuidora. A SolarInvest não pode garantir que os créditos sejam compensados no mesmo ciclo de faturamento em que o cliente solicitou a alteração.', tags: ['rateio', 'atraso', 'compensação', 'créditos', 'distribuidora', 'ciclo de faturamento'], priority: 'review' },
    { id: 'cliente-pode-comprar-sistema-leasing', question: 'O cliente pode comprar o sistema depois de aderir ao Leasing Solar?', shortAnswer: 'Sim. O contrato pode prever aquisição antecipada conforme regras comerciais vigentes.', answer: 'Sim. O cliente pode solicitar a compra antecipada do sistema após aderir ao Leasing Solar, conforme as condições previstas no contrato e na política comercial vigente da SolarInvest. O valor de aquisição pode variar de acordo com o momento da solicitação, prazo já cumprido, saldo contratual, regras de buyout e condições específicas da proposta. O SDR não deve informar valor de compra por conta própria; deve encaminhar a solicitação ao consultor.', tags: ['comprar sistema', 'compra antecipada', 'leasing', 'buyout', 'aquisição', 'valor residual', 'contrato', 'comprar depois'], priority: 'review' },
    { id: 'quando-comprar-sistema-leasing', question: 'Quando o cliente pode comprar o sistema no Leasing Solar?', shortAnswer: 'A compra antecipada depende das condições previstas no contrato.', answer: 'A possibilidade de compra antecipada depende das condições previstas no contrato de Leasing Solar e da política comercial vigente. O SDR deve informar que existe essa possibilidade, mas que a simulação de valor e o momento aplicável precisam ser confirmados por um consultor ou pela equipe responsável.', tags: ['comprar', 'leasing', 'compra antecipada', 'contrato', 'buyout', 'consultor', 'aquisição antecipada'], priority: 'review' },
    { id: 'solarinvest-controla-creditos', question: 'A SolarInvest controla a compensação de créditos?', shortAnswer: 'Não. Compensação, rateio e processamento na fatura são feitos pela distribuidora.', answer: 'Não. A compensação de energia, o rateio de créditos e o processamento na fatura são realizados pela distribuidora, conforme regras regulatórias. A SolarInvest pode acompanhar e orientar, mas não controla os prazos e critérios internos da distribuidora.', tags: ['créditos', 'creditos', 'compensação', 'rateio', 'distribuidora'], priority: 'review' },
  ]},
  { category: 'Monitoramento, Wi-Fi e manutenção', description: 'Conectividade, monitoramento remoto e impacto operacional.', items: [
    { id: 'wifi-importante', question: 'Por que o Wi-Fi é importante?', shortAnswer: 'Permite monitoramento remoto e acompanhamento da geração.', answer: 'A conexão com a internet permite o monitoramento remoto da usina. O cliente deve manter a rede Wi-Fi estável e informar previamente qualquer mudança de provedor, roteador, senha ou configuração que possa afetar o monitoramento.', tags: ['wifi', 'wi-fi', 'internet', 'monitoramento'], priority: 'qualified' },
    { id: 'usina-sem-internet', question: 'O que acontece se a usina ficar sem internet?', shortAnswer: 'Pode impedir monitoramento remoto, embora o sistema possa continuar gerando.', answer: 'A falta de internet pode impedir o monitoramento remoto preciso da geração. O sistema pode continuar gerando, mas a SolarInvest pode ficar sem acesso aos dados. Em contratos de leasing, falhas recorrentes de conexão podem impactar a forma de cobrança, conforme previsto nas regras contratuais.', tags: ['sem internet', 'wifi', 'monitoramento', 'cobrança'], priority: 'review' },
  ]},
  { category: 'Garantias, seguro e responsabilidades', description: 'Coberturas, mau uso e responsabilidades.', items: [
    { id: 'sistema-tem-garantia', question: 'O sistema tem garantia?', shortAnswer: 'Sim, há garantias de fabricante e responsabilidades contratuais conforme o caso.', answer: 'Sim. Os equipamentos possuem garantias de fabricante e o contrato pode prever responsabilidades específicas da SolarInvest durante o período de leasing. Cada caso deve ser analisado conforme o tipo de falha, prazo, origem do problema e cobertura aplicável.', tags: ['garantia', 'fabricante', 'contrato'], priority: 'qualified' },
    { id: 'cobre-danos-mau-uso', question: 'A SolarInvest cobre danos por mau uso?', shortAnswer: 'Não necessariamente; casos de mau uso e intervenção não autorizada podem não estar cobertos.', answer: 'Não necessariamente. Danos por mau uso, negligência, intervenção de terceiros não autorizados, alterações indevidas ou falhas na instalação elétrica interna do imóvel podem não estar cobertos. O SDR deve orientar que cada caso será avaliado tecnicamente.', tags: ['mau uso', 'danos', 'negligência', 'terceiros'], priority: 'disqualified' },
  ]},
  { category: 'Sistemas on-grid, off-grid e híbridos', description: 'Diferenças técnicas e atendimento em falta de energia.', items: [
    { id: 'sistema-funciona-falta-energia', question: 'O sistema funciona quando falta energia?', shortAnswer: 'Na maioria dos sistemas on-grid, não. Para backup, avaliar híbrido com baterias.', answer: 'Na maioria dos projetos convencionais, o sistema é on-grid, ou seja, conectado à rede da distribuidora. Por segurança, quando falta energia da rede, o inversor desliga automaticamente. Para manter energia durante apagões, é necessário estudar um sistema híbrido com baterias ou solução de backup específica.', tags: ['falta energia', 'apagão', 'on-grid', 'híbrido', 'bateria'], priority: 'review' },
    { id: 'diferenca-ongrid-offgrid-hibrido', question: 'Qual a diferença entre on-grid, off-grid e híbrido?', shortAnswer: 'On-grid usa rede; off-grid usa baterias sem rede; híbrido combina rede, solar e baterias.', answer: 'Sistema on-grid é conectado à rede da distribuidora e normalmente não possui baterias. Sistema off-grid é independente da rede e usa baterias para armazenar energia. Sistema híbrido combina conexão com a rede, geração solar e baterias, podendo atender cargas críticas em caso de falta de energia, quando projetado para essa finalidade.', tags: ['on-grid', 'off-grid', 'híbrido', 'baterias', 'falta energia'], priority: 'review' },
    { id: 'solarinvest-vende-baterias', question: 'A SolarInvest vende baterias?', shortAnswer: 'Sim, dependendo da necessidade e análise técnica específica.', answer: 'Sim, dependendo da necessidade do cliente. Projetos com baterias exigem análise técnica específica, definição de cargas críticas, autonomia desejada, potência dos equipamentos e orçamento diferenciado.', tags: ['bateria', 'backup', 'híbrido'], priority: 'review' },
  ]},
  { category: 'Objeções comerciais', description: 'Respostas padrão para objeções frequentes.', items: [
    { id: 'objecao-esta-caro', question: '“Está caro.”', shortAnswer: 'Comparar com a conta atual e economia ao longo do contrato.', answer: 'Entendo. O ponto principal é comparar com o que o cliente já paga hoje para a distribuidora e com a economia ao longo do contrato. No Leasing Solar, o objetivo é reduzir o gasto mensal sem exigir a compra imediata do sistema. Posso encaminhar sua conta para uma análise mais precisa?', tags: ['caro', 'preço', 'objeção', 'economia'], priority: 'review' },
    { id: 'objecao-vou-pensar', question: '“Vou pensar.”', shortAnswer: 'Convidar o cliente a pensar com números reais após análise da conta.', answer: 'Claro. Para que você pense com números reais, o ideal é analisarmos sua última conta de energia. Assim conseguimos verificar se o projeto qualifica e qual seria a estimativa de economia.', tags: ['vou pensar', 'objeção', 'conta de energia'], priority: 'review' },
    { id: 'objecao-ja-tenho-orcamento', question: '“Já tenho orçamento.”', shortAnswer: 'Apresentar a SolarInvest como alternativa, especialmente sem investimento total de compra.', answer: 'Ótimo. A SolarInvest pode avaliar o seu perfil e apresentar uma alternativa, especialmente se você tiver interesse em reduzir a conta sem fazer o investimento total de compra do sistema. Pode me enviar sua última conta de energia para análise?', tags: ['orçamento', 'concorrente', 'alternativa'], priority: 'review' },
    { id: 'objecao-nao-quero-financiamento', question: '“Não quero financiamento.”', shortAnswer: 'Explicar que leasing não é financiamento bancário tradicional.', answer: 'Perfeito. O Leasing Solar justamente não é tratado como um financiamento bancário tradicional. Nesse modelo, a SolarInvest investe no sistema e o cliente paga uma mensalidade pelo uso da usina, conforme contrato.', tags: ['financiamento', 'leasing', 'banco'], priority: 'qualified' },
  ]},
  { category: 'Leads não qualificados', description: 'Casos de desqualificação e respostas seguras.', items: [
    { id: 'solarinvest-compra-energia-terceiros', question: 'A SolarInvest compra energia de terceiros?', shortAnswer: 'Não compra energia gerada por terceiros nem intermedeia créditos externos.', answer: 'Não. A SolarInvest não compra energia gerada por terceiros nem intermedeia comercialização de créditos de usinas externas. Nosso foco é desenvolver, instalar, operar e monitorar projetos próprios ou vender sistemas fotovoltaicos aos clientes.', tags: ['comprar energia', 'vender energia', 'terceiros', 'créditos'], priority: 'disqualified' },
    { id: 'responder-quer-vender-energia', question: 'O que responder para quem quer vender energia?', shortAnswer: 'Informar que a SolarInvest não compra energia de terceiros nem intermedeia créditos.', answer: 'Resposta padrão: Agradecemos o contato, mas atualmente a SolarInvest não atua comprando energia de terceiros nem intermediando venda de créditos de energia. Nosso foco é atender clientes que desejam reduzir seus custos com energia por meio de projetos desenvolvidos ou operados pela própria SolarInvest.', tags: ['vender energia', 'resposta padrão', 'não qualificado'], priority: 'disqualified' },
    { id: 'solarinvest-aluga-terrenos', question: 'A SolarInvest aluga terrenos?', shortAnswer: 'No momento, não capta terrenos para locação, arrendamento ou usinas de terceiros.', answer: 'No momento, a SolarInvest não está captando terrenos para locação, arrendamento ou implantação de usinas de terceiros. Caso essa estratégia mude no futuro, a empresa poderá reavaliar oportunidades.', tags: ['terreno', 'aluga terrenos', 'arrendamento', 'usina'], priority: 'disqualified' },
    { id: 'responder-oferecem-terreno', question: 'O que responder quando oferecem um terreno?', shortAnswer: 'Agradecer e informar que a empresa não busca novas áreas para usinas solares.', answer: 'Resposta padrão: Agradecemos pelo contato e pela oferta. No momento, a SolarInvest não está buscando novas áreas para implantação de usinas solares. Nosso foco atual é atender clientes consumidores de energia com perfil compatível para leasing, venda ou monitoramento.', tags: ['terreno', 'oferta', 'área', 'resposta padrão'], priority: 'disqualified' },
    { id: 'solarinvest-compra-arrenda-areas', question: 'A SolarInvest compra ou arrenda áreas para usinas?', shortAnswer: 'No momento, não compra nem arrenda áreas para implantação de usinas de terceiros.', answer: 'Atualmente, a SolarInvest não está em processo ativo de compra, locação ou arrendamento de áreas para implantação de usinas de terceiros. O SDR deve agradecer o contato e registrar apenas se houver orientação específica da gestão.', tags: ['terreno', 'áreas', 'arrenda', 'compra terreno', 'usinas'], priority: 'disqualified' },
    { id: 'fornecedor-oferecendo-produto', question: 'O que fazer com fornecedor oferecendo produto?', shortAnswer: 'Coletar dados e encaminhar internamente apenas se houver orientação da diretoria.', answer: 'O SDR deve agradecer, coletar nome, empresa, telefone, e-mail e segmento, e encaminhar internamente apenas se houver orientação da diretoria. Esse tipo de contato não deve ser tratado como lead comercial.', tags: ['fornecedor', 'produto', 'parceria', 'não lead'], priority: 'disqualified' },
  ]},
  { category: 'Scripts de atendimento', description: 'Mensagens prontas para WhatsApp e passagem ao consultor.', items: [
    { id: 'mensagem-inicial-whatsapp', question: 'Mensagem inicial para WhatsApp', shortAnswer: 'Saudação objetiva para direcionar o atendimento.', answer: 'Olá, tudo bem? Sou da SolarInvest. Para eu te direcionar corretamente, você busca reduzir sua conta de energia com energia solar, comprar um sistema fotovoltaico ou tirar alguma dúvida específica?', tags: ['whatsapp', 'mensagem inicial', 'script'], priority: 'qualified' },
    { id: 'mensagem-pedir-conta-energia', question: 'Mensagem para pedir conta de energia', shortAnswer: 'Solicitar foto ou PDF da última conta para análise.', answer: 'Para fazermos uma análise correta, por favor me envie uma foto ou PDF da sua última conta de energia. Com ela conseguimos verificar consumo, distribuidora, unidade consumidora e viabilidade inicial do projeto.', tags: ['conta de energia', 'script', 'pdf'], priority: 'qualified' },
    { id: 'mensagem-abaixo-perfil-minimo', question: 'Mensagem para cliente abaixo do perfil mínimo', shortAnswer: 'Explicar mínimos de Goiás e DF e oferecer análise futura ou alternativas.', answer: 'Obrigado pelas informações. Neste momento, para Leasing Solar, priorizamos projetos com conta média a partir de R$ 500,00 em Goiás e R$ 600,00 no Distrito Federal. Pelo valor informado, talvez o projeto ainda não tenha viabilidade nesse modelo, mas podemos manter seu contato para uma análise futura ou avaliar outras alternativas.', tags: ['abaixo do mínimo', '500', '600', 'script'], priority: 'disqualified' },
    { id: 'mensagem-nao-qualificado-terreno', question: 'Mensagem para lead não qualificado por terreno', shortAnswer: 'Informar que a SolarInvest não está captando terrenos.', answer: 'Agradecemos pelo contato e pela oferta. No momento, a SolarInvest não está captando terrenos para locação, arrendamento ou implantação de novas usinas. Nosso foco atual é atender consumidores que desejam reduzir seus custos com energia.', tags: ['terreno', 'não qualificado', 'script'], priority: 'disqualified' },
    { id: 'mensagem-encaminhar-consultor', question: 'Mensagem para encaminhar ao consultor', shortAnswer: 'Confirmar potencial inicial e avisar que o consultor fará avaliação detalhada.', answer: 'Perfeito. Pelas informações iniciais, seu perfil pode ter viabilidade para análise. Vou encaminhar seus dados e sua conta de energia para um consultor da SolarInvest, que poderá fazer uma avaliação mais detalhada e te apresentar as melhores opções.', tags: ['consultor', 'encaminhar', 'script'], priority: 'qualified' },
  ]},
  { category: 'Encaminhamento para consultor', description: 'Quando avançar ou segurar um lead.', items: [
    { id: 'quando-encaminhar-consultor', question: 'Quando encaminhar para consultor?', shortAnswer: 'Quando tem perfil mínimo, interesse real, dados básicos e conta enviada ou prometida.', answer: 'Encaminhar quando o cliente estiver dentro do perfil mínimo de conta, demonstrar interesse real, enviar ou se comprometer a enviar a conta de energia, informar cidade/estado, tipo de imóvel e tiver perfil compatível com leasing ou venda.', tags: ['encaminhar', 'consultor', 'qualificado'], priority: 'qualified' },
    { id: 'quando-nao-encaminhar-consultor', question: 'Quando não encaminhar para consultor?', shortAnswer: 'Não encaminhar terrenos, venda de energia, parcerias, emprego, fornecedores ou conta muito baixa.', answer: 'Não encaminhar leads que desejam apenas vender terreno, vender energia, oferecer parceria de usina, procurar emprego, vender equipamento, oferecer serviço ou contatos com conta muito abaixo do mínimo para leasing, salvo orientação expressa da gestão.', tags: ['não encaminhar', 'desqualificar', 'terreno', 'vender energia'], priority: 'disqualified' },
  ]},
];
